CoviDoc/Models/Patient.cs
using CoviDoc.Common;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using static CoviDoc.Models.Enums;

namespace CoviDoc.Models
{
    /// <summary>
    /// Cannot update the DateRegistered of patient
    /// </summary>
    public class Patient
    {
        public Guid ID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$",
            ErrorMessage = "Must start with a capital letter and cannot include special characters.")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$",
            ErrorMessage ="Must start with a capital letter and cannot include special characters.")]
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$",
            ErrorMessage = "Must start with a capital letter and cannot include special characters.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        private string _fullName;
        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                if (string.IsNullOrEmpty(MiddleName))
                {
                    return $"{FirstName} {LastName}";
                }
                else
                {
                    return $"{FirstName} {MiddleName} {LastName}";
                }
            }            
        }

        [Required]
        [Display(Name = "ID/Passport No.")]
        public string IdNumber { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public DateTime DoB { get; set; }

        [Required]
        [JsonProperty(Required = Required.Always, PropertyName = "Gender")]
        [JsonConverter(typeof(StringEnumConverter))]
        public Gender Gender { get; set; }

        public string Nationality { get; set; }

        private string _mobileNumber;
        //  @"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$"
        [Required]
       // [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Not a valid mobile number.")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile Number")]
        public string MobileNumber
        {
            get => _mobileNumber;
            set => _mobileNumber = Helpers.FormatMobileNumber(value);
        }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        public string County { get; set; }
        public string Constituency { get; set; }
        public string Ward { get; set; }
        public bool IsAdult { get; set; }
        public bool IsActive { get; set; } = true;

        [DataType(DataType.Date)]
        [Display(Name = "Date of Reg.")]
        public DateTime DateRegistered { get; set; }
        public List<Guid> ChildrenIds { get; set; }
    }
}

CoviDoc/ViewModels/PatientViewModel.cs
using CoviDoc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoviDoc.ViewModels
{
    public class PatientViewModel
    {
        public Patient Patient { get; set; }
        public DiagnosisReport DiagnosisReport { get; set; }
        public IEnumerable<SelectListItem> Countries { get; set; }
        public IEnumerable<SelectListItem> Counties { get; set; }
        public IEnumerable<SelectListItem> Constituencies { get; set; }
        public IEnumerable<SelectListItem> Wards { get; set; }
        public TestCentre TestCentre { get; set; }
    }
}

CoviDoc/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using CoviDoc.Common;
using CoviDoc.Models;
using CoviDoc.Models.Interfaces;
using CoviDoc.ViewModels;
using MessagingService;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace CoviDoc.Controllers
{
    //[Route("api/[controller]")]
    [ApiController]
    public class PatientsController : ControllerBase
    {

        private readonly string _emailPassword;
        private readonly string _emailUserName;
        readonly string _emailFrom;
        readonly IPatientRepository _patientRepository;
        readonly IHealthCertificateRepository _healthCertificateRepository;

        public PatientsController(IPatientRepository patientRepository,
                                  IConfiguration configuration,
                                  IHealthCertificateRepository healthCertificateRepository)
        {
            _patientRepository = patientRepository;
            _healthCertificateRepository = healthCertificateRepository;
            _emailFrom = configuration["EmailConfigs:RegistrationsEmailAddresss"];
            _emailPassword = configuration["EmailConfigs:Password"];
            _emailUserName = configuration["EmailConfigs:UserName"];
        }

        [HttpGet]
        [Route("api/[controller]/{patientId}")]
        [Produces("application/json")]
        public async Task<IActionResult> GetPatientsAsync(Guid patientId)
        {
            if (patientId == Guid.Empty)
            {
                return NotFound();
            }

            var patient = await _patientRepository.GetPatient(patientId);

            if (patient == null)
            {
                return NotFound();
            }

            return Ok(patient);

        }

        // GET: api/Patients
        [HttpGet]
        [Route("api/[controller]")]
        [Produces("application/json")]
        public async Task<IActionResult> GetPatientsAsync(string idNumber, string name)
        {
            if (!string.IsNullOrEmpty(idNumber) && !string.IsNullOrEmpty(name))
            {
                return BadRequest();
            }

            List<Patient> patients = await _patientRepository.GetPatients();

            if (!string.IsNullOrEmpty(idNumber))
            {
                patients = patients.Where(p => p.IdNumber.Equals(idNumber, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            if (!string.IsNullOrEmpty(name))
            {
                patients = patients.Where(p => p.FullName.Contains(name, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            return Ok(patients);
        }

        // POST: api/Patients
        [HttpPost]
        [Route("api/[controller]")]
        public async Task<IActionResult> PostPatientAsync([FromBody] Patient patient)
        {
            try
            {
                if (patient != null)
                {
                    patient.ID = Guid.NewGuid();
                    patient.DateRegistered = DateTime.UtcNow.AddHours(3);
                    patient.MobileNumber = Helpers.FormatMobileNumber(patient.MobileNumber);
                    patient.IsAdult = Helpers.IsAdult(patient.DoB);
                    await _patientRepository.AddPatient(patient);

                    // Create Health Certificate
                    var qrCodeFileName = $"{patient.ID}.png";
                    var qrCodeUri = $"{Request.Scheme}://{Request.Host}{Url.Content($"~/MyCovid19Certificate/{qrCodeFileName}")}";
                    var qrCodeFileLocation = Path.Combine(Directory.GetCurrentDirectory(), "QRCodes", $"{qrCodeFileName}");
                    var certificateUri = string.Format("{0}://{1}/certificates/details/{2}", Request.Scheme, Request.Host, patient.ID.ToString());

                    // Generate QR Code
                    var qrCodeUrl = $"https://chart.googleapis.com/chart?cht=qr&chs={500}x{500}&chl={certificateUri}";
                    WebRequest webRequest = WebRequest.Create(qrCodeUrl);
                    using WebResponse webResponse = webRequest.GetResponse();
                    using Stream remoteStream = webResponse.GetResponseStream();
                    using StreamReader streamReader = new StreamReader(remoteStream);

                    // Save QR code to directory
                    var qrCodeImage = Image.FromStream(remoteStream);
                    qrCodeImage.Save(qrCodeFileLocation);

                    // Geneate Health certificate
                    var healthCertificate = new HealthCertificate
                    {
                        PatientId = patient.ID,
                        IdNumber = patient.IdNumber,
                        MobileNumber = patient.MobileNumber,
                        IsAdult = patient.IsAdult,
                        Name = patient.FullName,
                        BaseUrlLocation = qrCodeUri,
                        CertificateId = $"{patient.IdNumber}-{Helpers.GenerateCertificateId(5)}"
                    };
                    await _healthCertificateRepository.AddHealthCertificate(healthCertificate);

                    // Send Email to patient; if has email address
                    if (patient.EmailAddress != null)
                    {
                        string emailBody = GenerateEmailBody(patient, qrCodeUri);

                        if (emailBody != null)
                        {
                            Email email = new Email
                            {
                                From = _emailFrom,
                                To = patient.EmailAddress,
                                Subject = $"Registration Successful - {patient.FullName}",
                                Body = emailBody
                            };
                            await EmailProcessor.SendEmailAsync(email, _emailUserName, _emailPassword);
                        }
                    }

                    string patientUri = string.Format("{0}://{1}{2}/{3}", Request.Scheme, Request.Host, Request.Path.Value, patient.ID.ToString());

                    return Created(patientUri, patient);
                }
                return BadRequest();
            }
            catch (Exception ex)
            {
                return new JsonResult(ex.Message) { StatusCode = StatusCodes.Status404NotFound };
            }
        }

        private string GenerateEmailBody(Patient patient, string qrCodeUri)
        {
            string body = string.Empty;

            using (StreamReader reader = new StreamReader("./Resources/RegistrationsTemplate.html"))
            {
                body = reader.ReadToEnd();
            };
            body = body.Replace("{PatientFirstName}", patient.FirstName);
            body = body.Replace("{PatientFullName}", patient.FullName.ToUpper());
            body = body.Replace("{PatientIdNumber}", patient.IdNumber.ToUpper());
            body = body.Replace("{RegistrationDate}", patient.DateRegistered.ToString("dddd, dd MMMM yyyy hh:mm tt"));
            body = body.Replace("{LinkToCertificate}", qrCodeUri);
            body = body.Replace("{BaseUrl}", $"{Request.Scheme}://{Request.Host}");
            body = body.Replace("{QRCode}", qrCodeUri);

            return body;
        }

        // PUT: api/patients/5
        [HttpPut]
        [Route("api/[controller]/{patientId}")]
        [Produces("application/json")]
        public async Task<IActionResult> UpdatePatientAsync(Guid patientId, [FromBody] Patient patient)
        {
            if (patient == null || patientId == Guid.Empty)
            {
                return BadRequest();
            }
            // Check if patient exists
            var updatedPatient = await _patientRepository.GetPatient(patientId);

            if (updatedPatient == null)
            {
                return BadRequest();
            }

            updatedPatient.Constituency = patient.Constituency ?? updatedPatient.Constituency;
            updatedPatient.County = patient.County ?? updatedPatient.County;
            updatedPatient.DoB = patient.DoB;
            updatedPatient.FirstName = patient.FirstName ?? updatedPatient.FirstName;
            updatedPatient.Gender = patient.Gender;
            updatedPatient.IdNumber = patient.IdNumber ?? updatedPatient.IdNumber;
            updatedPatient.LastName = patient.LastName ?? updatedPatient.LastName;
            updatedPatient.MiddleName = patient.MiddleName ?? updatedPatient.MiddleName;
            updatedPatient.MobileNumber = patient.MobileNumber ?? updatedPatient.MobileNumber;
            updatedPatient.Nationality = patient.Nationality;
            updatedPatient.Ward = patient.Ward;

            await _patientRepository.UpdatePatient(updatedPatient);

            return Ok(updatedPatient);
        }

        // DELETE: api/patients/5
        [HttpDelete]
        [Route("api/[controller]/{patientId}")]
        public async Task<IActionResult> DeactivatePatientAsync(Guid patientId)
        {
            if (patientId == Guid.Empty)
            {
                return BadRequest();
            }
            // Check if patient exists
            var patient = await _patientRepository.GetPatient(patientId);
            ResponseViewModel response;

            if (patient == null)
            {
                response = new ResponseViewModel
                {
                    Code = StatusCodes.Status404NotFound,
                    Message = "Patient not found."
                };
                return NotFound(response);
            }

            await _patientRepository.DeactivatePatient(patientId);

            response = new ResponseViewModel
            {
                Code = StatusCodes.Status204NoContent,
                Message = "Patient deleted successfully."

CoviDoc/Views/Patient/Create.cshtml
@model CoviDoc.ViewModels.PatientViewModel

@{
    ViewData["Title"] = "Register Patient";
}

<h4>Register New Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Patient.FirstName" class="control-label"></label>
                <input asp-for="Patient.FirstName" class="form-control" />
                <span asp-validation-for="Patient.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.MiddleName" class="control-label"></label>
                <input asp-for="Patient.MiddleName" class="form-control" />
                <span asp-validation-for="Patient.MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.LastName" class="control-label"></label>
                <input asp-for="Patient.LastName" class="form-control" />
                <span asp-validation-for="Patient.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.IdNumber" class="control-label"></label>
                <input asp-for="Patient.IdNumber" class="form-control" />
                <span asp-validation-for="Patient.IdNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.DoB" class="control-label"></label>
                <input asp-for="Patient.DoB" class="form-control" />
                <span asp-validation-for="Patient.DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.Gender" class="control-label"></label>
                <select asp-for="Patient.Gender" class="form-control"
                        asp-items="Html.GetEnumSelectList<Enums.Gender>()"><option>-- Select Gender --</option></select>
                <span asp-validation-for="Patient.Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.Nationality" class="control-label"></label>
                <select asp-for="Patient.Nationality" class="form-control"
                        asp-items="@(new SelectList(Model.Countries, "Value", "Text"))"></select>
                <span asp-validation-for="Patient.Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.MobileNumber" class="control-label"></label>
                <input asp-for="Patient.MobileNumber" class="form-control" />
                <span asp-validation-for="Patient.MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.County" class="control-label"></label>
                <select asp-for="Patient.County" class="form-control" id="County"
                        asp-items="@(new SelectList(Model.Counties, "Value", "Text"))"></select>
                <span asp-validation-for="Patient.County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.Constituency" class="control-label"></label>
                <select asp-for="Patient.Constituency" class="form-control" id="Constituency"
                        asp-items="@(new SelectList(Model.Constituencies, "Value", "Text"))"></select>
                <span asp-validation-for="Patient.Constituency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patient.Ward" class="control-label"></label>
                <select asp-for="Patient.Ward" class="form-control" id="Ward"
                        asp-items="@(new SelectList(Model.Wards, "Value", "Text"))"></select>
                <span asp-validation-for="Patient.Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        $('#County').change(function () {
            var selectedCounty = $("#County").val();
            var constituencySelect = $('#Constituency');
            var wardSelect = $('#Ward');
            constituencySelect.empty();
            wardSelect.empty();
            if (selectedCounty != null && selectedCounty != '') {
                $.getJSON('@Url.Action("GetConstituencies")', { CountyName: selectedCounty }, function (constituencies) {
                    if (constituencies != null && !jQuery.isEmptyObject(constituencies)) {
                        constituencySelect.append($('<option/>', {
                            value: null,
                            text: ""
                        }));
                        wardSelect.append($('<option/>', {
                            value: null,
                            text: ""
                        }));
                        $.each(constituencies, function (index, constituency) {
                            constituencySelect.append($('<option/>', {
                                value: constituency.value,
                                text: constituency.text
                            }));
                        });
                    };
                });
            }
        });

        $('#Constituency').change(function () {
            console.log('Hello');
            var selectedCounty = $("#County").val();
            var selectedConstituency = $("#Constituency").val();
            var wardSelect = $('#Ward');
            wardSelect.empty();
            if (selectedCounty != null && selectedCounty != '' &&
                selectedConstituency != null && selectedConstituency != '') {
                $.getJSON('@Url.Action("GetWards")', { CountyName: selectedCounty, ConstituencyId: selectedConstituency }, function (wards) {
                    if (wards != null && !jQuery.isEmptyObject(wards)) {
                        console.log(wards);
                        wardSelect.append($('<option/>', {
                            value: null,
                            text: ""
                        }));
                        $.each(wards, function (index, ward) {
                            wardSelect.append($('<option/>', {
                                value: ward.value,
                                text: ward.text
                            }));
                        });
                    };
                });
            }
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoviDoc/Views/Patient/Delete.cshtml
@model CoviDoc.Models.Patient

@{
    ViewData["Title"] = "Delete Patient";
}

<h4>Are you sure you want to delete this patient?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationality)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Constituency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Constituency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ward)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ward)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdult)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdult)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateRegistered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateRegistered)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoviDoc/Views/Patient/Details.cshtml
@model CoviDoc.ViewModels.PatientViewModel

@{
    ViewData["Title"] = "Patient Details";
}

<h4>Patient Details</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.IdNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.IdNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.DoB)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.DoB)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.Nationality)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.Nationality)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.MobileNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.MobileNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.County)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.County)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.Constituency)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.Constituency)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.Ward)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.Ward)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.IsAdult)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.IsAdult)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.IsActive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patient.DateRegistered)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patient.DateRegistered)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiagnosisReport.TestStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiagnosisReport.TestStatus)
        </dd>
        @if (Model.DiagnosisReport.DiagnosisReportId != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DiagnosisReport.DateTested)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DiagnosisReport.DateTested)
            </dd>
        }
        @if (Model.TestCentre != null)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TestCentre.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TestCentre.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TestCentre.Ward)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TestCentre.Ward)
            </dd>
        }

    </dl>
</div>
<div>
    <a asp-action="Test" asp-route-id="@Model.Patient.ID">Test</a> |
    <a asp-action="Edit" asp-route-id="@Model.Patient.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CoviDoc/Views/Patient/Index.cshtml
@model IEnumerable<CoviDoc.Models.Patient>

@{
    ViewData["Title"] = "Registered Patients";
}

<h4>Registered Patients</h4>

<p>
    <a asp-action="Create">Add New</a>
</p>
<form asp-controller="Patients" asp-action="Index" method="get">
    <p>
        Id No. : <input type="text" name="IdNumber">
        <input type="submit" value="Filter" />
        Name: <input type="text" name="Name">
        <input type="submit" value="Filter" /> |
        <a asp-action="Index">List</a>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdult)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateRegistered)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAdult)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRegistered)
            </td>
            <td>
                <a asp-action="Test" asp-route-id="@item.ID">Test</a> |
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>